- gtdbtk/misc.py
> Fix check_install issues warnings.

- bin/gtdbtk
- gtdbtk/main.py
- gtdbtk/markers.py
- gtdbtk/trim_msa.py
I have moved the trim_msa.py script into the GTDB-Tk source code directory. GTDB-Tk align now supports the same custom trimming we plan to perform. The trim_msa.py script can still be run independently of GTDB-Tk if required. I also finalized the implementation for inferring trees with FastTree.
> Implements full custom MSA filtering and tree inference.

- README.md
- gtdbtk/VERSION
- gtdbtk/classify.py
> GTDBTk returns closest fastani reference genome

- bin/gtdbtk
- gtdbtk/trim_msa.py
Allows for reproducible trimming when using trim_msa.py as a stand-alone script.
> Added random seed to trim_msa.py to allow for reproducible results.

- bin/gtdbtk
- gtdbtk/classify.py
- gtdbtk/external/hmm_aligner.py
- gtdbtk/external/pfam_search.py
- gtdbtk/external/prodigal.py
- gtdbtk/external/tigrfam_search.py
- gtdbtk/main.py
- gtdbtk/markers.py
- gtdbtk/misc.py
- gtdbtk/relative_distance.py
- gtdbtk/tools.py
- gtdbtk/trim_msa.py
In one special situation ( a userleaf has no closest pplacer genome, has close genomes detected by fastani but the closest genome is less the FASTANI_SPECIES_THRESHOLD percentage ) the other_related_references field required a pplacer_leafnode that didn't exist. ( line 678 of classify.py)
This has been fixed.
> remove biolib,mpld3,jinja dependencies. Fix bug classify case

- .gitignore
- bin/gtdbtk
- gtdbtk/biolib_lite/prodigal_biolib.py
- gtdbtk/external/prodigal.py
- gtdbtk/main.py
- gtdbtk/markers.py
Checks to see if input files are empty before gene calling.
Checks to see if any genes were actually called.
Exit from prodigal if an error is encountered on any genome (unless --force is specified).
> Prodigal input checking, exit conditions, and --force

- gtdbtk/classify.py
- gtdbtk/exceptions.py
- gtdbtk/external/fastani.py
- gtdbtk/external/fasttree.py
- gtdbtk/main.py
Note that the diff isn't matching up correctly, the only big change was removing the try block and the FastANI code.
> External classes for FastANI and FastTree

- README.md
- gtdbtk/VERSION
- gtdbtk/classify.py
* Pplacer taxonomy is now available in the summary file.
* FastANI species assignment will be selected over phylogenetic placement (Topology case).
> 0.3.1 Update

- gtdbtk/classify.py
- optimized calculation of internal RED value for user genomes; time reduced from >30 min to seconds
> Optimization of RED calculations.

- README.md
- bin/gtdbtk
- gtdbtk/external/pfam_search.py
- gtdbtk/external/tigrfam_search.py
- gtdbtk/main.py
- gtdbtk/markers.py
* --genes parameter indicates that the directory contains amino acids
* typically usage will require -x faa or files won't be found
* resolves #13
> Supply genomes as called genes

- README.md
- gtdbtk/external/fastani.py
- gtdbtk/external/hmm_aligner.py
hmmalign and fastANI progress shown in console.
Changed how jobs in multiprocessing queue for the aforementioned tasks are handled. Instead of partitioning, it's consumed from a shared queue.
> Display progress updates

- README.md
- bin/gtdbtk
- gtdbtk/classify.py
- gtdbtk/external/pplacer.py
- gtdbtk/main.py
`--pplacer_cpus` argument overrides the `--cpus` argument for pplacer placement, resolves #195
> Pplacer threads #195

- gtdbtk/external/hmm_aligner.py
- gtdbtk/external/prodigal.py
- gtdbtk/external/tigrfam_search.py
- gtdbtk/main.py
> Expand user path and improve progress str

- README.md
- bin/gtdbtk
- gtdbtk/ani_rep.py
- gtdbtk/config/output.py
- gtdbtk/external/fastani.py
- gtdbtk/external/mash.py
- gtdbtk/main.py
> calculate ani to representative genomes

- README.md
- gtdbtk/external/hmm_aligner.py
- gtdbtk/external/pfam_search.py
- gtdbtk/external/tigrfam_search.py
- gtdbtk/io/marker/copy_number.py
- gtdbtk/io/marker/tophit.py
- gtdbtk/io/prodigal/tln_table_summary.py
- gtdbtk/markers.py
- setup.py
- tests/test_gtdbtk/test_io/test_marker/test_copy_number.py
- tests/test_gtdbtk/test_io/test_marker/test_tophit.py
- tests/test_gtdbtk/test_io/test_prodigal/test_tln_table_summary.py
* Wrapped functionality into classes
* Consider multiple unique hits
Resolves #230
> Improved marker identification

- bin/gtdbtk
- gtdbtk/VERSION
- gtdbtk/ani_rep.py
- gtdbtk/biolib_lite/common.py
- gtdbtk/biolib_lite/newick.py
- gtdbtk/biolib_lite/taxonomy.py
- gtdbtk/classify.py
- gtdbtk/config/output.py
- gtdbtk/decorate.py
- gtdbtk/external/fastani.py
- gtdbtk/external/fasttree.py
- gtdbtk/external/mash.py
- gtdbtk/main.py
- gtdbtk/markers.py
- gtdbtk/reroot_tree.py
Added decorate method; initial implementation and testing of full de novo workflow; minor improvements to logging; added taxonomy to output files of ani_rep
> Added decorate method and full implementation of de novo workflow

- bin/gtdbtk
- gtdbtk/VERSION
- gtdbtk/biolib_lite/taxonomy.py
- gtdbtk/config/config.py
- gtdbtk/infer_ranks.py
- gtdbtk/main.py
- gtdbtk/relative_distance.py
- Added the infer_rank method which established the taxonomic ranks of internal nodes of user trees based on RED
> Added the infer_rank method

- docs/announcements.md
- gtdbtk/classify.py
- gtdbtk/external/pfam_search.py
- gtdbtk/external/pplacer.py
- gtdbtk/external/prodigal.py
- gtdbtk/external/tigrfam_search.py
- gtdbtk/io/marker/tophit.py
- gtdbtk/io/prodigal/tln_table.py
- gtdbtk/markers.py
- gtdbtk/tools.py
Skip genomes already processed during identify
> Checkpointing #207

- docs/_config.yml
- docs/announcements.md
- gtdbtk/external/fastani.py
- tests/test_gtdbtk/test_external/test_fastani.py
> Fix parsing of FastANI v1 output files resolves #251

- gtdbtk/classify.py
- gtdbtk/cli.py
- gtdbtk/main.py
> allow user to set af threshold in classify(_wf), resolves #289

- .github/workflows/docs_update.yml
Added back **options.scratch_dir** and **options.recalculate_red** in the function **parse_options** for the command _classify_wf_ to prevent an error "AttributeError: 'Namespace' object has no attribute".
> Refined options parser for classify_wf

- gtdbtk/config/output.py
- gtdbtk/external/prodigal.py
- gtdbtk/main.py
- gtdbtk/markers.py
> Failed genomes mgmt

- docs/src/commands/convert_to_itol.rst
Docummentation for `convert_to_itol` tool. Thank for adding it!
> `convert_to_itol` docs

- gtdbtk/main.py
- gtdbtk/tools.py
> fix(root/de_novo_wf): Add additional checks to outgroup_taxon to restrict ranges of input.

- scripts/gtdb_to_ncbi_majority_vote.py
> fix(474): Fixed NCBI majority vote script to work with ANI screen

- gtdbtk/external/pypfam/Scan/PfamScan.py
> Add cutoff arguments to PfamScan

- docs/src/announcements.rst
- docs/src/changelog.rst
- setup.py
Pydantic requirements added  ( to solve #529 and #528)
> Merge staging to fix pydantic depencies

- Dockerfile
- README.md
- docs/src/changelog.rst
- docs/src/commands/ani_rep.rst
- docs/src/commands/check_install.rst
- docs/src/commands/classify.rst
- docs/src/commands/classify_wf.rst
- docs/src/faq.rst
- docs/src/files/mash_distances.msh.rst
- docs/src/files/summary.tsv.rst
- docs/src/installing/index.rst
- docs/src/references.rst
- gtdbtk/ani_rep.py
- gtdbtk/ani_screen.py
- gtdbtk/classify.py
- gtdbtk/cli.py
- gtdbtk/config/common.py
- gtdbtk/config/output.py
- gtdbtk/exceptions.py
- gtdbtk/external/skani.py
- gtdbtk/files/classify_summary.py
- gtdbtk/main.py
- gtdbtk/misc.py
- gtdbtk/tools.py
- scripts/rename_UBAs/prepare_gtdbtk_package.py
- scripts/verify_official_package.py
- tests/test_gtdbtk/test_external/test_fasttree.py
- tests/test_gtdbtk/test_external/test_skani.py
Merging the skani branch to replace FastANI
> Skani branch

- gtdbtk/classify.py
- gtdbtk/main.py
- gtdbtk/markers.py
The summary files are still produces even if all genomes fail the prodigal step
> feat(fix of #576):
